"""
Training workflow logic.
Loads features, trains the classifier, and saves the ModelBundle.
"""

import json
import warnings
from pathlib import Path
from typing import Dict, Optional

import numpy as np

from renal_vision.features.dataset import FeatureDatasetProcessor

from .models import train_classifier

# Columns generated by features that are NOT features
METADATA_COLUMNS = {
    "case",
    "case_id",
    "patient_id",
    "image_path",
    "seg_path",
    "label",
    "class_id",
    "lesion_id",
    "volume_voxels",
    "augmented",
    "aug_id",
    "class_name",
}


def load_class_config(json_path: Optional[str]) -> Dict[int, str]:
    """Load class names from JSON (e.g. {'1': 'Tumor'})."""
    if not json_path:
        return {}

    with open(json_path, "r") as f:
        data = json.load(f)
        # Handle different json structures
        if "class_names" in data:
            mapping = data["class_names"]
        else:
            mapping = data

        return {int(k): str(v) for k, v in mapping.items()}


def run_training(
    data_path: str,
    output_dir: str,
    model_type: str = "logistic",
    class_config_path: Optional[str] = None,
    extractor_config_path: Optional[str] = None,
    tree_max_depth: int = 5,
) -> None:
    """
    Execute the training pipeline.

    Args:
        data_path: Path to the training features (Parquet/CSV).
        output_dir: Directory to save the model.
        model_type: 'logistic', 'tree', or 'xgboost'.
        class_config_path: JSON file defining class names (e.g. {1: 'Tumor'}).
        extractor_config_path: JSON file from features describing extraction settings.
        tree_max_depth: Hyperparameter for tree-based models.
    """
    print(f"Loading training data from {data_path}...")
    df = FeatureDatasetProcessor.load_features(data_path)

    # 1. Identify Feature Columns
    # We dynamically select all columns that are not known metadata
    feature_names = [c for c in df.columns if c not in METADATA_COLUMNS]

    if not feature_names:
        raise ValueError(
            f"No feature columns found in input. Metadata columns excluded: {METADATA_COLUMNS}"
        )
    print(f"Detected {len(feature_names)} features: {feature_names}")

    # 2. Prepare X and y
    # We assume 'class_id' is the target column based on features output
    if "class_id" not in df.columns:
        if "label" in df.columns:
            target_col = "label"
        else:
            raise ValueError("Input data missing 'class_id' or 'label' column.")
    else:
        target_col = "class_id"

    X = df[feature_names].values
    y = df[target_col].values.astype(int)

    # 3. Resolve Class Names
    # If config provided, use it. Otherwise, generate generic names.
    unique_classes = [int(cl) for cl in np.unique(y)]
    n_classes = len(unique_classes)

    loaded_names = load_class_config(class_config_path)
    class_names: Dict[int, str] = {}

    for cls in unique_classes:
        if cls in loaded_names:
            class_names[cls] = loaded_names[cls]
        else:
            class_names[cls] = f"Class {cls}"
            warnings.warn(f"No name provided for Class {cls}. Using default.")

    print(f"Training on {len(df)} samples ({n_classes} classes).")
    print(f"Class mapping: {class_names}")

    # 4. Load/Create Extractor Config
    # This is crucial for Inference later. If the user didn't provide the config
    # from the feature extraction step, we create a minimal default to prevent crash.
    if extractor_config_path and Path(extractor_config_path).exists():
        with open(extractor_config_path, "r") as f:
            extractor_config = json.load(f)
    else:
        warnings.warn(
            "No extractor config provided. Inference may require manual configuration. "
            "Assuming default Radiomics settings."
        )
        extractor_config = {"type": "radiomics", "feature_names": feature_names}

    # 5. Train Model
    model_bundle = train_classifier(
        X=X,
        y=y,
        model_type=model_type,
        feature_names=feature_names,
        class_names=class_names,
        extractor_config=extractor_config,
        tree_max_depth=tree_max_depth,
        apply_log_transform=True,
    )

    # 6. Save
    out_path = Path(output_dir) / "model.pkl"
    model_bundle.save(out_path)
    print(f"Successfully saved model to {out_path}")
